FROM node:20-alpine

ARG ENVIRONMENT=production

ENV NODE_ENV ENVIRONMENT
ENV IS_CONTAINER_ENV true

USER node

RUN mkdir /home/node/app
WORKDIR /home/node/app

COPY --chown=1000:1000 . .

RUN npm ci --omit dev

EXPOSE 8080

CMD [ "node", "--enable-source-maps", "dist/bin/Server.mjs" ]
