components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  parameters:
    ObjectId:
      in: path
      name: id
      required: true
      schema:
        type: string
        pattern: "[a-fA-F0-9]{24}"
  schemas:
    ValidationErrors:
      type: array
      items:
        type: object
        properties:
          dataPath:
            type: string
          keyword:
            type: string
          message:
            type: string
          params:
            type: object
          schemaPath:
            type: string
  responses:
    200Null:
      description: The request was successful 
    400ModelValidation:
      description: The supplied parameters are invalid
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ValidationErrors"
    404NotFound:
      description: The requested item wasn't found
    500Internal:
      description: An unspecified error has occurred
